services:
  postgres:
    image: postgres:alpine
    container_name: Megaads-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    networks:
      - cluster
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: Megaads-api
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_PORT=${API_PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '${API_PORT}:${API_PORT}'
    networks:
      - cluster

volumes:
  postgres_data:

networks:
  cluster:
    driver: bridge